### PR TITLE
Don't convert null to the string "null"

### PR DESCRIPTION
**Pull request by porsager**
I hope this is an acceptable change, although I don't know the complete requirements of this package, but this fix will solve https://github.com/mapbox/mapbox-gl-js/issues/8497.

I can't think of a reason it would make sense to have null as a string `"null"` because of the ambiguity it brings. Rather make it an empty string if there is a requirement for it to be a string.

### CODE REVIEW

**Comment by cafca** [comment]
Is this project still maintained by mapbox? Who can merge this PR? @anandthakker

**Comment by mourner** [comment]
@cafca yep! Sorry for the late response — I'll do some much-needed maintenance on vt-pbf this week, including this PR.

**Comment by bailycase99** [comment]
Any update on this PR? It's still an issue :)

**Review by mourner — APPROVED** [review]

**Comment by ericfischer** [comment]
This change causes vector tiles to be created that violate the current vector tile spec and cannot be uploaded to Mapbox. https://github.com/mapbox/vt-pbf/issues/42

**Comment by mourner** [comment]
@ericfischer thanks for uncovering this! Please check out #43 as a potential fix.

**Pull request merged**
